// Generated by CoffeeScript 1.6.3
(function() {
  var OssEasy, async, fs, generateRandomId, ossAPI, path, _;

  _ = require("underscore");

  ossAPI = require('oss-client');

  fs = require("fs");

  async = require("async");

  path = require("path");

  generateRandomId = function() {
    return "" + ((Math.random() * 36 >> 0).toString(36)) + ((Math.random() * 36 >> 0).toString(36)) + (Date.now().toString(36));
  };

  OssEasy = (function() {
    function OssEasy(ossOptions, targetBucket) {
      this.targetBucket = targetBucket;
      if (!(_.isString(ossOptions.accessKeyId) && _.isString(ossOptions.accessKeySecret) && _.isString(this.targetBucket))) {
        throw new Error("missing input parameter: accessKeyId:" + ossOptions.accessKeyId + ", accessKeySecret: " + ossOptions.accessKeySecret + ", targetBucket:" + targetBucket);
        return;
      }
      ossOptions['timeout'] = ossOptions['timeout'] || 5 * 60 * 1000;
      this.oss = new ossAPI.OssClient(ossOptions);
    }

    OssEasy.prototype.readFile = function(filepath, options, callback) {
      var pathToTempFile;
      console.log("[oss-easy::readFile] " + filepath);
      pathToTempFile = path.join("/tmp/", generateRandomId());
      this.downloadFile(filepath, pathToTempFile, function(err) {
        if (err != null) {
          if (_.isFunction(callback)) {
            return callback(err);
          }
        } else {
          return fs.readFile(pathToTempFile, options, callback);
        }
      });
    };

    OssEasy.prototype.writeFile = function(remoteFilePath, data, callback) {
      var args, contentType;
      console.log("[oss-easy::writeFile] " + filename);
      if (Buffer.isBuffer(data)) {
        contentType = "application/octet-stream";
      } else {
        contentType = "text/plain";
        data = new Buffer(data);
      }
      args = {
        bucket: this.targetBucket,
        object: remoteFilePath,
        srcFile: data,
        contentType: contentType
      };
      this.oss.putObject(args, callback);
    };

    OssEasy.prototype.uploadFile = function(remoteFilePath, pathToFile, callback) {
      var args;
      console.log("[oss-easy::uploadFile] " + pathToFile + " -> " + remoteFilePath);
      args = {
        bucket: this.targetBucket,
        object: remoteFilePath,
        srcFile: pathToFile
      };
      this.oss.putObject(args, callback);
    };

    OssEasy.prototype.uploadFileBatch = function(filenames, basePath, callback) {
      var err, filename, i, _i, _len,
        _this = this;
      if (!Array.isArray(filenames)) {
        err = "bad argument, filenames:" + filenames;
        console.error("[oss-easy::uploadFileBatch] " + err);
        if (_.isFunction(callback)) {
          callback(err);
        }
        return;
      }
      if (_.isFunction(basePath) && (callback == null)) {
        callback = basePath;
        basePath = null;
      }
      if (_.isString(basePath) && basePath.length > 0) {
        filenames = filenames.concat();
        for (i = _i = 0, _len = filenames.length; _i < _len; i = ++_i) {
          filename = filenames[i];
          filenames[i] = path.join(basePath, filename);
        }
      }
      async.eachSeries(filenames, function(filename, eachCallback) {
        return _this.uploadFile(path.basename(filename), filename, eachCallback);
      }, callback);
    };

    OssEasy.prototype.downloadFile = function(filename, pathToFile, callback) {
      var args;
      console.log("[oss-easy::downloadFile] " + pathToFile + " <- " + filename);
      args = {
        bucket: this.targetBucket,
        object: filename,
        dstFile: pathToFile
      };
      this.oss.getObject(args, callback);
    };

    OssEasy.prototype.downloadFileBatch = function(filenames, basePath, callback) {
      var err,
        _this = this;
      if (!(Array.isArray(filenames) && _.isString(basePath) && basePath.length > 0)) {
        err = "bad argument, filenames:" + filenames;
        console.error("[oss-easy::downloadFileBatch] " + err);
        if (_.isFunction(callback)) {
          callback(err);
        }
        return;
      }
      async.eachSeries(filenames, function(filename, eachCallback) {
        return _this.downloadFile(filename, path.join(basePath, filename), eachCallback);
      }, callback);
    };

    OssEasy.prototype.deleteFile = function(filename, callback) {
      var args;
      console.log("[oss-easy::deleteFile] " + filename);
      args = {
        bucket: this.targetBucket,
        object: filename
      };
      this.oss.deleteObject(args, callback);
    };

    OssEasy.prototype.deleteFileBatch = function(filenames, callback) {
      var err,
        _this = this;
      if (!Array.isArray(filenames)) {
        err = "bad argument, filenames:" + filenames;
        console.error("[oss-easy::deleteFileBatch] " + err);
        if (_.isFunction(callback)) {
          callback(err);
        }
        return;
      }
      async.eachSeries(filenames, function(filename, eachCallback) {
        return _this.deleteFile(filename, eachCallback);
      }, callback);
    };

    return OssEasy;

  })();

  module.exports = OssEasy;

}).call(this);
